<a href="https://colab.research.google.com/github/gmrampe/Data_Analysis/blob/main/Numpy_Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#sorting

In [ ]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
print(a)

[4 7 0 3 8 2 5 1 6 9]


In [ ]:
b = np.sort(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a)

[4 7 0 3 8 2 5 1 6 9]


In [ ]:
d = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
print(d)

[4 7 0 3 8 2 5 1 6 9]


In [ ]:
d.sort()
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#argsort()

In [ ]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
print(a)

[4 7 0 3 8 2 5 1 6 9]


In [ ]:
b = a.argsort()
print(b)

[2 7 5 3 0 6 8 1 4 9]


In [ ]:
#usecase--> assignment

In [ ]:
b = np.array([5,7,3,1,10])
c = b.argsort()
print(c)

[3 2 0 1 4]


In [ ]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

b = np.sort(a) #row-wise, axis = 1

In [ ]:
print(b)

[[  4  23  43]
 [  3  12  89]
 [  0  69 420]]


In [ ]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

b = np.sort(a, axis = 0)

In [ ]:
print(b)

[[ 12   4   0]
 [ 23  89   3]
 [ 69 420  43]]


In [ ]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

b = np.sort(a, axis = 1)

In [ ]:
print(b)

[[  4  23  43]
 [  3  12  89]
 [  0  69 420]]


In [ ]:
#element-wise operations

In [ ]:
a = np.arange(5)
b = np.ones(5)
print(a)

[0 1 2 3 4]


In [ ]:
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
a*b

array([0., 1., 2., 3., 4.])

In [ ]:
a = np.arange(1, 13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
b = np.arange(2, 14).reshape(3,4)
print(b)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [ ]:
b.shape

(3, 4)

In [ ]:
a.shape

(3, 4)

In [ ]:
#element-wise operation
print(a+b)

[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]]


In [ ]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(b)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [ ]:
#element-wise multiplication
print(a*b)

[[  2   6  12  20]
 [ 30  42  56  72]
 [ 90 110 132 156]]


In [ ]:
#Matrix Multiplication

'''
1. np.dot
2. @ operator
3. np.matmul
'''

'\n1. np.dot\n2. @ operator\n3. np.matmul\n'

In [ ]:
#Matrix Multiplication

a = np.arange(1,13).reshape(3,4)
b = np.arange(2,14).reshape(4,3)

In [ ]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [ ]:
#way1
c = np.dot(a,b)
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [ ]:
#way2
c = a@b
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [ ]:
#way3
c = np.matmul(a,b)
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [ ]:
# (5,) -> 1D same as (5,1) ->2D

In [ ]:
a = np.arange(5)
b = np.arange(1,6)
print(a)

[0 1 2 3 4]


In [ ]:
print(b)

[1 2 3 4 5]


In [ ]:
c = np.dot(a,b)

In [ ]:
print(c)

40


In [ ]:
#HW--> To understand what exactly happened

---
## Vectorization
- Vectorization in NumPy refers to performing operations on entire arrays or array elements simultaneously, which is significantly faster and more efficient than using explicit loops.


In [ ]:
#Vectorization -> np

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
def solve(n):
  if n%2 == 0:
    n += 2
  else:
    n -= 2

  return n

In [ ]:
solve(4)

6

In [ ]:
solve(7)

5

In [ ]:
solve(a)

ValueError: ignored

In [ ]:
new_solve = np.vectorize(solve)

In [ ]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
new_solve(a)

array([ 2, -1,  4,  1,  6,  3,  8,  5, 10,  7])

In [ ]:
#Doubt

# output to this is None a = np.array([4,7,0,3,8,2,5,1,6,9]) print(a.sort())

In [ ]:
a = np.array([5,8,2,4,9])
print(a)
b = a.sort()

[5 8 2 4 9]


In [ ]:
print(b)

None


In [ ]:
print(a)

[2 4 5 8 9]


#Broadcasting

![bro.jpg](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/047/364/original/download.jpeg?1694345633)

In [ ]:
#case1

In [ ]:
a = np.arange(0,40,10)
print(a)

[ 0 10 20 30]


In [ ]:
#np.tile()

a = np.tile(a, (3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [ ]:
a = np.arange(0,40,10)
d = np.tile(a, (3,2))
print(d)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [ ]:
d.shape

(3, 8)

In [ ]:
a = np.arange(0,40,10)
a = np.tile(a, (3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [ ]:
a = a.T
print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [ ]:
b = np.arange(0,3)
print(b)

[0 1 2]


In [ ]:
b = np.tile(b, (4,1))
print(b)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


In [ ]:
a.shape

(4, 3)

In [ ]:
b.shape

(4, 3)

In [ ]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
#case2

In [ ]:
print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [ ]:
b = np.arange(0,3)
print(b)

[0 1 2]


In [ ]:
print(a+b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
'''
Explanation:
a -> (4,3)
b -> (3,) --> (1,3)

(4,3)
(1,3)

output: (4,3)

'''

'\nExplanation:\na -> (4,3)\nb -> (3,) --> (1,3)\n\n(4,3)\n(1,3)\n\noutput: (4,3)\n\n'

In [ ]:
#case3

In [ ]:
a = np.arange(0,40,10)
print(a)

[ 0 10 20 30]


In [ ]:
a = a.reshape(4,1)
print(a)

[[ 0]
 [10]
 [20]
 [30]]


In [ ]:
b = np.arange(0,3)
print(b)

[0 1 2]


In [ ]:
a.shape

(4, 1)

In [ ]:
b.shape

(3,)

In [ ]:
print(a+b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
'''
Explanation:

(4,1)
(3,) --> (1, 3)


(4,1)
(1,3)

output: (4,3)
'''

'\nExplanation:\n\n(4,1)\n(3,) --> (1, 3)\n\n\n(4,1)\n(1,3)\n\noutput: (4,3)\n'

In [ ]:
#Quiz:

a = np.arange(8).reshape(2,4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
b = np.arange(16).reshape(4,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#Will this work?
a+b

ValueError: ignored

In [ ]:
'''
Explanation:

(4,4)
(2,4)

Across every dimension:
Rule1: both are same
or
Rule2: atleast one of them should be 1
'''

'\nExplanation:\n\n(4,4)\n(2,4)\n\nAcross every dimension:\nRule1: both are same\nor\nRule2: atleast one of them should be 1\n'

In [ ]:
#Quiz:

A = np.arange(12).reshape(3, 4)
B = np.array([1, 2, 3])
A+B
'''
A -> (3,4)
B -> (3,) --> (1,3)

(3,4)
(1,3)

Error

'''

ValueError: ignored

In [ ]:
'''
Quiz

Given two arrays of shape
Array A of shape (8, 1, 6, 1)
Array B of shape (7, 1, 5)
Is broadcasting possible in this case? If yes, what will be the shape of output ?
'''

'\nQuiz\n\nGiven two arrays of shape\nArray A of shape (8, 1, 6, 1)\nArray B of shape (7, 1, 5)\nIs broadcasting possible in this case? If yes, what will be the shape of output ?\n'

In [ ]:
'''
Soln:

A -> (8, 1, 6, 1)
B -> (7, 1, 5) --> (1, 7, 1, 5)


A -> (8, 1, 6, 1)
B -> (1, 7, 1, 5)

What will be the shape after broadcasting
(8, 7, 6, 5)

'''

'\nSoln:\n\nA -> (8, 1, 6, 1)\nB -> (7, 1, 5) --> (1, 7, 1, 5)\n\n\nA -> (8, 1, 6, 1)\nB -> (1, 7, 1, 5)\n\nWhat will be the shape after broadcasting\n(8, 7, 6, 5)\n\n'