<a href="https://colab.research.google.com/github/gmrampe/Data_Analysis/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a= np.array(range(16))

In [ ]:
a.shape

(16,)

In [ ]:
a.ndim

1

In [ ]:
#reshape

In [ ]:
b = a.reshape(8,2)

In [ ]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
print(b)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
b.shape

(8, 2)

In [ ]:
b.ndim

2

In [ ]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape(4,5)

ValueError: ignored

In [ ]:
a.reshape(8,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a.reshape(4,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
a.reshape(-1, 5)

ValueError: ignored

In [ ]:
a.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a = a.reshape(8,2)

In [ ]:
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
a.ndim

2

In [ ]:
a.shape

(8, 2)

In [ ]:
len(a) #rows

8

In [ ]:
len(a[0]) #cols

2

In [ ]:
a.reshape(-1,-1)

ValueError: ignored

In [ ]:
#Transpose

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a.shape

(3, 4)

In [ ]:
#Transpose
b= a.T

In [ ]:
print(b)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
b.shape

(4, 3)

In [ ]:
#n x m --> after transpose --> m x n

In [ ]:
#Quiz
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[1]

array([4, 5, 6])

In [ ]:
a[1][2]

6

In [ ]:
a[1,2]

6

In [ ]:
a[2,0]

7

In [ ]:
# a[row, col]

In [ ]:
#Multi-indexing in 2D Numpy Arrays

In [ ]:
a = np.array([100,200,300,400,500,600])

In [ ]:
a.shape

(6,)

In [ ]:
a.ndim

1

In [ ]:
a[2,3]

IndexError: ignored

In [ ]:
a[[ 2, 5]] #multi-indexing

array([300, 600])

In [ ]:
print(a)

[100 200 300 400 500 600]


In [ ]:
print(a[[2,3,4,1,2,2]])

[300 400 500 200 300 300]


In [ ]:
#multi-indexing in 2D

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
a[2,1]

7

In [ ]:
a[0,2]

2

In [ ]:
a[[2, 0] , [1, 2]]

array([7, 2])

In [ ]:
#Task: Use multi-indexing in 2D to print the principal digonal elements of the above given np array


a[[0, 1, 2] , [0, 1, 2]]

array([0, 4, 8])

In [ ]:
#slicing

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a[:2] #first 2 rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a[: , :2] #first 2 columns

array([[0, 1],
       [4, 5],
       [8, 9]])

In [ ]:
a[: , 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
#Fancy indexing in 2D

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
a[a<6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Quiz

a = np.array([7,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1

In [ ]:
print(a)

[ 7  1 -1  3 -1  5]


In [ ]:

a = np.array([7,8,4,9,3,2])
a[a%2 == 1]

array([7, 9, 3])

In [ ]:

a = np.array([7,8,4,9,3,2])
a[a%2 == 1] = -1
print(a)

[-1  8  4 -1 -1  2]


In [ ]:
a = np.arange(14).reshape(2,7)
print(a)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]


In [ ]:
a[[0,0, 1] , [0,2,5]]

array([ 0,  2, 12])

In [ ]:
#aggregate functions

In [ ]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
np.sum(a) #sum of all the values in a

55

In [ ]:
np.mean(a)

5.5

In [ ]:
np.min(a)

1

In [ ]:
np.max(a)

10

In [ ]:
#aggregate functions on 2D

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 0 -> Vertical axis
# 1 -> Horizontal axis

In [ ]:
#row-wise sum: [6, 22, 38 ]

In [ ]:
np.sum(a, axis = 1)

array([ 6, 22, 38])

In [ ]:
# [12, 15, 18, 21]
np.sum(a, axis = 0)

array([12, 15, 18, 21])

In [ ]:
#Logical operations

In [ ]:
a = np.array([5,7,2, 8, 1])
print(a)

[5 7 2 8 1]


In [ ]:
print(a < 3)

[False False  True False  True]


In [ ]:
#np.all() np.any()

In [ ]:
np.all(a < 3)

False

In [ ]:
np.all(a < 30)

True

In [ ]:
np.any(a < 3)

True

In [ ]:
np.any(a > 30)

False

In [ ]:
#Quiz

a = np.array([0,2,3])
b = np.array([1,3,5])


In [ ]:
print(a)

[0 2 3]


In [ ]:
print(b)

[1 3 5]


In [ ]:
#element-wise operation/comparison
a >= b

array([False, False, False])

In [ ]:
print(a + b)

[1 5 8]


In [ ]:
arr = np.array([-3,4,27,34,-2, 10, -45,-11,4, 9 ])
arr

array([ -3,   4,  27,  34,  -2,  10, -45, -11,   4,   9])

#### What if we want to update an array based on condition?

Suppose you are given an array of integers and you want to update it based on following condition:
- if element is > 0, change it to +1
- if element < 0, change it to -1.

> **How will you do it?**


In [ ]:
print(arr)

[ -3   4  27  34  -2  10 -45 -11   4   9]


In [ ]:
arr[arr < 0] = -1
arr[arr > 0] = 1
print(arr)

[-1  1  1  1 -1  1 -1 -1  1  1]


In [ ]:
#where()

Function signature:
`np.where(condition, x, y)`

This functions returns an ndarray whose elements are chosen from `x` or `y` depending on condition.



In [ ]:
arr = np.array([-3,4,27,34,-2, 10, -45,-11,4, 9 ])
arr

array([ -3,   4,  27,  34,  -2,  10, -45, -11,   4,   9])

In [ ]:
b = np.where(arr > 0, 1, -1)

In [ ]:
print(b)

[-1  1  1  1 -1  1 -1 -1  1  1]


In [ ]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0])
print(np.where(arr))


(array([0, 1, 2, 3, 4, 6, 7, 8]),)


In [ ]:
#Use-case using case-study

In [ ]:
data = np.loadtxt("fit.txt", dtype = "str")

In [ ]:
print(data)

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

In [ ]:
data.shape

(96, 6)

There are 96 records and each record has 6 features. </br>
These features are:
- Date
- Step count
- Mood
- Calories Burned
- Hours of sleep
- activity status

In [ ]:
print(data[0])

['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']


In [ ]:
print(data[:5])

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']]


In [ ]:
print(data[:, 0])

['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
 '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
 '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
 '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
 '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
 '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
 '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
 '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
 '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
 '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
 '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
 '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
 '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
 '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
 '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2017'
 '20-12-20

In [ ]:
data_t = data.T
print(data_t)

[['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
  '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
  '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
  '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
  '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
  '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
  '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
  '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
  '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
  '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
  '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
  '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
  '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
  '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
  '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2

In [ ]:
step_count = data_t[1]
print(step_count)

['5464' '6041' '25' '5461' '6915' '4545' '4340' '1230' '61' '1258' '3148'
 '4687' '4732' '3519' '1580' '2822' '181' '3158' '4383' '3881' '4037'
 '202' '292' '330' '2209' '4550' '4435' '4779' '1831' '2255' '539' '5464'
 '6041' '4068' '4683' '4033' '6314' '614' '3149' '4005' '4880' '4136'
 '705' '570' '269' '4275' '5999' '4421' '6930' '5195' '546' '493' '995'
 '1163' '6676' '3608' '774' '1421' '4064' '2725' '5934' '1867' '3721'
 '2374' '2909' '1648' '799' '7102' '3941' '7422' '437' '1231' '1696'
 '4921' '221' '6500' '3575' '4061' '651' '753' '518' '5537' '4108' '5376'
 '3066' '177' '36' '299' '1447' '2599' '702' '133' '153' '500' '2127'
 '2203']


In [ ]:
step_count = np.array(step_count, dtype = "int")
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
mood = data_t[2]
print(mood)

['Neutral' 'Sad' 'Sad' 'Sad' 'Neutral' 'Sad' 'Sad' 'Sad' 'Sad' 'Sad' 'Sad'
 'Sad' 'Happy' 'Sad' 'Sad' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Neutral'
 'Neutral' 'Neutral' 'Neutral' 'Happy' 'Neutral' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Happy' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Sad'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Sad' 'Neutral'
 'Neutral' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Happy' 'Neutral' 'Neutral'
 'Sad' 'Neutral' 'Sad' 'Neutral' 'Neutral' 'Sad' 'Sad' 'Sad' 'Sad' 'Happy'
 'Neutral' 'Happy' 'Neutral' 'Sad' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Sad'
 'Sad' 'Happy' 'Neutral' 'Neutral' 'Happy']


In [ ]:
b = np.unique(mood)

In [ ]:
print(b)

['Happy' 'Neutral' 'Sad']


In [ ]:
#avg step counts that you take when your mood is Happy

In [ ]:
mood == "Happy"

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [ ]:
happy_step_count = step_count[mood == "Happy"]
print(happy_step_count)

[4732  330 4550 4435 4779 1831 2255  539 5464 4068 4683 4033 6314  614
 3149 4005 4880 4136  705  269 4275 5999 4421 6930 5195  546  493  995
 3608  774 1421 4064 2725 5934 1867 7422 5537 5376  153 2203]


In [ ]:
#step counts when mood is sad
sad_step_count = step_count[mood == "Sad"]
print(sad_step_count)

[6041   25 5461 4545 4340 1230   61 1258 3148 4687 3519 1580 2822  181
 6676 3721 1648  799 1696  221 4061  651  753  518  177   36  299  702
  133]


In [ ]:
happy_step_count = step_count[mood == "Happy"]
print(happy_step_count)

[4732  330 4550 4435 4779 1831 2255  539 5464 4068 4683 4033 6314  614
 3149 4005 4880 4136  705  269 4275 5999 4421 6930 5195  546  493  995
 3608  774 1421 4064 2725 5934 1867 7422 5537 5376  153 2203]


In [ ]:
avg_happy = np.mean(happy_step_count)
print(avg_happy)

3392.725


In [ ]:
#give me step counts when the mood was either Happy or Neutral

In [ ]:
happy_neutral_steps = step_count[(mood == "Happy") | (mood == "Neutral")]


In [ ]:
print(happy_neutral_steps)

[5464 6915 4732 3158 4383 3881 4037  202  292  330 2209 4550 4435 4779
 1831 2255  539 5464 6041 4068 4683 4033 6314  614 3149 4005 4880 4136
  705  570  269 4275 5999 4421 6930 5195  546  493  995 1163 3608  774
 1421 4064 2725 5934 1867 2374 2909 7102 3941 7422  437 1231 4921 6500
 3575 5537 4108 5376 3066 1447 2599  153  500 2127 2203]


In [ ]:
'''
or --> |
and --> &
'''

'\nor --> |\nand --> &\n'

In [ ]:
#doubt
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a[2:]

array([[ 8,  9, 10, 11]])

In [ ]:
a = [4,7,2]
a1= np.array(a)
print(a1)

[4 7 2]


In [ ]:
a = [[1,4], [6,7]]
a1 = np.array(a)
print(a1)

[[1 4]
 [6 7]]


In [ ]:
a = np.arange(4)
b = np.arange(5)
a+b

ValueError: ignored

In [ ]:
a = np.array([100,200,300,400,500,600])
a[2,3]

IndexError: ignored

In [ ]:
a[ [2, 5] ]

array([300, 600])